[versions]
agp = "9.1.0"
coreKtx = "1.17.0"
publish = "0.36.0"
kotlin = "2.3.20"
test = "1.7.0"
uiautomator = "2.4.0-beta02"
orchestrator = "1.6.1"
truth = "1.4.5"
testparameterinjector = "1.21"
mockk = "1.14.9"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "test" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "test" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "test" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-test-uiautomator-shell = { group = "androidx.test.uiautomator", name = "uiautomator-shell", version.ref = "uiautomator" }
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "orchestrator" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
testparameterinjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testparameterinjector" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }

